package com.example.data.repository

import android.util.Log
import com.example.data.model.DailyForecastItem
import com.example.data.model.HourlyForecastItem
import com.example.data.model.SevereWeatherAlert
import com.google.firebase.Firebase
import com.google.firebase.ai.GenerativeModel
import com.google.firebase.ai.ai
import com.google.firebase.ai.type.content
import com.google.firebase.ai.type.generationConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.withContext
import java.util.Locale

/**
 * Data model representing structured natural language weather intelligence generated by Firebase AI.
 */
data class WeatherSummaryResult(
    val headline: String,
    val narrativeSummary: String,
    val clothingAdvice: String,
    val outdoorWindow: String,
    val cautionNote: String? = null,
    val keyHighlights: List<String> = emptyList(),
    val rawAiResponse: String = ""
)

/**
 * Data model for activity-specific weather recommendations.
 */
data class ActivityRecommendation(
    val activityName: String,
    val isRecommended: Boolean,
    val recommendationSummary: String,
    val bestTimeWindow: String,
    val safetyTips: List<String> = emptyList()
)

/**
 * Data model for wardrobe and thermal comfort guidance.
 */
data class WardrobeRecommendation(
    val summary: String,
    val primaryLayers: List<String>,
    val accessories: List<String>,
    val umbrellaNeeded: Boolean
)

/**
 * Repository responsible for processing weather telemetry data and generating
 * natural language summaries, lifestyle insights, wardrobe guidance, and hazard
 * analysis using the Firebase AI SDK (Gemini 3.5 Flash).
 */
class WeatherAiSummaryRepository(
    private val modelName: String = "gemini-3.5-flash"
) {

    private val generativeModel: GenerativeModel by lazy {
        Firebase.ai.generativeModel(
            modelName = modelName,
            generationConfig = generationConfig {
                temperature = 0.4f
                topP = 0.95f
                topK = 40
            },
            systemInstruction = content {
                text(
                    """
                    You are an intelligent, expert meteorologist and environmental advisor for an advanced glassmorphic weather application.
                    Analyze the provided real-time weather telemetry data accurately and synthesize clear, engaging, and highly practical natural language summaries.
                    Tone: Professional, friendly, modern, concise, and actionable.
                    Avoid markdown asterisks or bold syntax when plain text is requested.
                    Focus on human-centric impacts: what conditions feel like, what to wear, safety directives, and optimal timing for outdoor activities.
                    """.trimIndent()
                )
            }
        )
    }

    /**
     * Processes full weather data and generates a comprehensive natural language summary with highlights.
     */
    suspend fun generateDailyWeatherSummary(
        weather: CompleteWeatherData,
        isFahrenheit: Boolean = false
    ): WeatherSummaryResult = withContext(Dispatchers.IO) {
        val telemetryContext = buildTelemetryPrompt(weather, isFahrenheit)
        val prompt = """
            Analyze this weather telemetry for ${weather.city.name} and provide a comprehensive daily summary.
            Return your response in the following structured format with clearly labeled sections:
            
            HEADLINE: (A catchy, descriptive 5-8 word summary of today's conditions)
            SUMMARY: (A 2-3 sentence overview covering current feel, temperature trend, and sky status)
            CLOTHING: (Specific, practical clothing advice tailored to the temperature and wind/rain)
            OUTDOOR_WINDOW: (The best hour or time of day for outdoor exercise or errands)
            CAUTION: (Any weather hazards, high UV, precipitation risk, or 'None')
            HIGHLIGHTS: (3 short bullet points of key takeaways separated by semicolons)
            
            Telemetry:
            $telemetryContext
        """.trimIndent()

        try {
            val response = generativeModel.generateContent(prompt)
            val text = response.text?.trim()
            if (!text.isNullOrBlank()) {
                parseStructuredSummary(text, weather, isFahrenheit)
            } else {
                generateFallbackSummary(weather, isFahrenheit)
            }
        } catch (e: Exception) {
            Log.w(TAG, "Firebase AI summary generation encountered an error; using fallback synthesizer: ${e.message}")
            generateFallbackSummary(weather, isFahrenheit)
        }
    }

    /**
     * Generates a concise 2-sentence executive audio / Sky Intelligence briefing.
     */
    suspend fun generateBriefingText(
        weather: CompleteWeatherData,
        isFahrenheit: Boolean = false
    ): String = withContext(Dispatchers.IO) {
        val telemetryContext = buildTelemetryPrompt(weather, isFahrenheit)
        val prompt = """
            Given this weather telemetry for ${weather.city.name}, generate a concise 2-sentence executive briefing.
            Sentence 1: Current condition, temperature, and what to wear.
            Sentence 2: Best outdoor window or key precipitation/wind alert.
            Plain text only without markdown formatting or bullet points.
            
            Telemetry:
            $telemetryContext
        """.trimIndent()

        try {
            val response = generativeModel.generateContent(prompt)
            val generated = response.text?.trim()
            if (!generated.isNullOrBlank()) {
                generated.replace("**", "").replace("*", "")
            } else {
                generateFallbackBriefing(weather, isFahrenheit)
            }
        } catch (e: Exception) {
            Log.w(TAG, "Firebase AI briefing generation failed: ${e.message}")
            generateFallbackBriefing(weather, isFahrenheit)
        }
    }

    /**
     * Evaluates weather telemetry to provide activity-specific feasibility and timing advice
     * (e.g., Running, Cycling, Photography, Outdoor Dining, Hiking).
     */
    suspend fun generateActivityRecommendation(
        activityName: String,
        weather: CompleteWeatherData,
        isFahrenheit: Boolean = false
    ): ActivityRecommendation = withContext(Dispatchers.IO) {
        val telemetry = buildTelemetryPrompt(weather, isFahrenheit)
        val prompt = """
            Evaluate weather conditions in ${weather.city.name} for the activity: "$activityName".
            Provide your evaluation in this format:
            RECOMMENDED: (YES or NO or CAUTION)
            BEST_WINDOW: (e.g., "7:00 AM - 10:00 AM" or "Late Afternoon after rain clears")
            SUMMARY: (1-2 sentences on why conditions are suitable or unsuitable)
            TIPS: (2-3 practical tips separated by semicolons)
            
            Telemetry:
            $telemetry
        """.trimIndent()

        try {
            val response = generativeModel.generateContent(prompt)
            val text = response.text ?: ""
            parseActivityRecommendation(activityName, text, weather)
        } catch (e: Exception) {
            Log.w(TAG, "Firebase AI activity recommendation failed: ${e.message}")
            fallbackActivityRecommendation(activityName, weather)
        }
    }

    /**
     * Evaluates temperature, humidity, wind, and precipitation to create structured wardrobe advice.
     */
    suspend fun generateWardrobeRecommendation(
        weather: CompleteWeatherData,
        isFahrenheit: Boolean = false
    ): WardrobeRecommendation = withContext(Dispatchers.IO) {
        val telemetry = buildTelemetryPrompt(weather, isFahrenheit)
        val prompt = """
            Based on this weather telemetry for ${weather.city.name}, suggest an optimal outfit and accessories.
            Format:
            SUMMARY: (1 sentence overall outfit recommendation)
            LAYERS: (Comma-separated clothing layers, e.g. "Thermal undershirt, Merino wool sweater, Waterproof shell")
            ACCESSORIES: (Comma-separated accessories, e.g. "Polarized sunglasses, Compact umbrella, Touchscreen gloves")
            UMBRELLA: (YES or NO)
            
            Telemetry:
            $telemetry
        """.trimIndent()

        try {
            val response = generativeModel.generateContent(prompt)
            val text = response.text ?: ""
            parseWardrobeRecommendation(text, weather)
        } catch (e: Exception) {
            Log.w(TAG, "Firebase AI wardrobe recommendation failed: ${e.message}")
            fallbackWardrobeRecommendation(weather)
        }
    }

    /**
     * Answers ad-hoc natural language questions regarding the current weather conditions.
     */
    suspend fun answerWeatherQuestion(
        question: String,
        weather: CompleteWeatherData,
        isFahrenheit: Boolean = false
    ): String = withContext(Dispatchers.IO) {
        val query = question.trim()
        if (query.isBlank()) return@withContext "Please ask a question about current or upcoming weather."

        val telemetry = buildTelemetryPrompt(weather, isFahrenheit)
        val prompt = """
            User Question: "$query"
            
            Answer this question accurately, concisely (2-3 sentences), and naturally using the weather telemetry for ${weather.city.name}.
            Do not include asterisks or markdown syntax.
            
            Telemetry:
            $telemetry
        """.trimIndent()

        try {
            val response = generativeModel.generateContent(prompt)
            val text = response.text?.trim()
            if (!text.isNullOrBlank()) {
                text.replace("**", "").replace("*", "")
            } else {
                fallbackAnswerQuestion(query, weather, isFahrenheit)
            }
        } catch (e: Exception) {
            Log.w(TAG, "Firebase AI Q&A failed: ${e.message}")
            fallbackAnswerQuestion(query, weather, isFahrenheit)
        }
    }

    /**
     * Streams real-time natural language summary tokens from Firebase AI SDK.
     */
    fun generateWeatherSummaryStream(
        weather: CompleteWeatherData,
        isFahrenheit: Boolean = false
    ): Flow<String> = flow {
        val telemetry = buildTelemetryPrompt(weather, isFahrenheit)
        val prompt = "Provide a lively, descriptive meteorological briefing for ${weather.city.name} today:\n$telemetry"

        try {
            generativeModel.generateContentStream(prompt).collect { chunk ->
                chunk.text?.let { emit(it) }
            }
        } catch (e: Exception) {
            Log.w(TAG, "Streaming failed, emitting fallback: ${e.message}")
            emit(generateFallbackBriefing(weather, isFahrenheit))
        }
    }.flowOn(Dispatchers.IO)

    // ==========================================
    // Telemetry Formatting & Processing Helpers
    // ==========================================

    /**
     * Transforms raw weather data into a clean, structured text context for the LLM.
     */
    fun buildTelemetryPrompt(weather: CompleteWeatherData, isFahrenheit: Boolean): String {
        val tempUnit = if (isFahrenheit) "°F" else "°C"
        val speedUnit = if (isFahrenheit) "mph" else "km/h"
        val curTemp = formatTemp(weather.currentTempC, isFahrenheit)
        val feelTemp = formatTemp(weather.apparentTempC, isFahrenheit)
        val maxTemp = formatTemp(weather.todayMaxTempC, isFahrenheit)
        val minTemp = formatTemp(weather.todayMinTempC, isFahrenheit)
        val windSpeed = if (isFahrenheit) (weather.windSpeedKmh * 0.621371).toInt() else weather.windSpeedKmh.toInt()

        val hourlySnippet = weather.hourlyList.take(12).joinToString("; ") {
            val t = formatTemp(it.tempC, isFahrenheit)
            "${it.hourLabel}: $t$tempUnit, rain ${it.precipitationProb}%"
        }

        val dailySnippet = weather.dailyList.take(5).joinToString("; ") {
            val maxT = formatTemp(it.maxTempC, isFahrenheit)
            val minT = formatTemp(it.minTempC, isFahrenheit)
            "${it.dayLabel}: max $maxT$tempUnit / min $minT$tempUnit, precip ${it.precipitationProb}%"
        }

        val alertsSummary = if (weather.activeAlerts.isNotEmpty()) {
            weather.activeAlerts.joinToString(" | ") { "${it.event} (${it.severity}): ${it.headline}" }
        } else {
            "No active severe alerts"
        }

        return """
            Location: ${weather.city.name}, ${weather.city.country ?: weather.city.countryCode ?: ""}
            Condition: ${weather.condition.title} - ${weather.condition.description}
            Current Temperature: $curTemp$tempUnit (Feels like $feelTemp$tempUnit)
            Today's High/Low: High $maxTemp$tempUnit / Low $minTemp$tempUnit
            Relative Humidity: ${weather.humidityPct}%
            Wind: $windSpeed $speedUnit
            Precipitation Today: ${weather.precipitationMm} mm (Current pop: ${weather.currentPrecipProb}%)
            UV Index Max: ${String.format(Locale.US, "%.1f", weather.currentUvIndex)}
            Surface Pressure: ${weather.surfacePressureHpa.toInt()} hPa
            Sun Cycle: Sunrise ${weather.sunCycle.sunriseFormatted}, Sunset ${weather.sunCycle.sunsetFormatted} (${weather.sunCycle.daylightDurationFormatted} daylight)
            Lunar Phase: ${weather.sunCycle.lunarPhase?.phaseName ?: "N/A"} (${weather.sunCycle.lunarPhase?.illuminationPct ?: 0}% illumination)
            Active Alerts: $alertsSummary
            Next 12 Hours Forecast: $hourlySnippet
            Upcoming 5-Day Trend: $dailySnippet
        """.trimIndent()
    }

    private fun formatTemp(tempC: Double, isFahrenheit: Boolean): Int {
        return if (isFahrenheit) {
            ((tempC * 9 / 5) + 32).toInt()
        } else {
            tempC.toInt()
        }
    }

    // ==========================================
    // Response Parsing Helpers
    // ==========================================

    private fun parseStructuredSummary(
        text: String,
        weather: CompleteWeatherData,
        isFahrenheit: Boolean
    ): WeatherSummaryResult {
        var headline = "${weather.condition.title} in ${weather.city.name}"
        var summary = ""
        var clothing = ""
        var outdoorWindow = "Mid-afternoon"
        var caution: String? = null
        val highlights = mutableListOf<String>()

        val lines = text.lines()
        for (line in lines) {
            val trimmed = line.trim()
            when {
                trimmed.startsWith("HEADLINE:", ignoreCase = true) -> {
                    headline = trimmed.substringAfter(":").trim().removeSurrounding("\"")
                }
                trimmed.startsWith("SUMMARY:", ignoreCase = true) -> {
                    summary = trimmed.substringAfter(":").trim()
                }
                trimmed.startsWith("CLOTHING:", ignoreCase = true) -> {
                    clothing = trimmed.substringAfter(":").trim()
                }
                trimmed.startsWith("OUTDOOR_WINDOW:", ignoreCase = true) -> {
                    outdoorWindow = trimmed.substringAfter(":").trim()
                }
                trimmed.startsWith("CAUTION:", ignoreCase = true) -> {
                    val rawCaution = trimmed.substringAfter(":").trim()
                    if (!rawCaution.equals("none", ignoreCase = true) && rawCaution.isNotBlank()) {
                        caution = rawCaution
                    }
                }
                trimmed.startsWith("HIGHLIGHTS:", ignoreCase = true) -> {
                    val items = trimmed.substringAfter(":").split(";")
                    highlights.addAll(items.map { it.trim().removePrefix("-").trim() }.filter { it.isNotBlank() })
                }
            }
        }

        if (summary.isBlank()) {
            summary = text.replace("**", "").replace("*", "").take(300)
        }
        if (clothing.isBlank()) {
            clothing = "Wear comfortable seasonal attire for ${formatTemp(weather.currentTempC, isFahrenheit)}°."
        }

        return WeatherSummaryResult(
            headline = headline,
            narrativeSummary = summary,
            clothingAdvice = clothing,
            outdoorWindow = outdoorWindow,
            cautionNote = caution,
            keyHighlights = highlights.ifEmpty { listOf("${weather.condition.title} conditions", "UV Index ${weather.currentUvIndex}", "${weather.currentPrecipProb}% chance of rain") },
            rawAiResponse = text
        )
    }

    private fun parseActivityRecommendation(
        activityName: String,
        text: String,
        weather: CompleteWeatherData
    ): ActivityRecommendation {
        var recommended = true
        var bestWindow = "Afternoon"
        var summary = text
        val tips = mutableListOf<String>()

        for (line in text.lines()) {
            val trimmed = line.trim()
            when {
                trimmed.startsWith("RECOMMENDED:", ignoreCase = true) -> {
                    val status = trimmed.substringAfter(":").trim().uppercase(Locale.ROOT)
                    recommended = status.startsWith("YES") || status.contains("GOOD") || status.contains("FAVORABLE")
                }
                trimmed.startsWith("BEST_WINDOW:", ignoreCase = true) -> {
                    bestWindow = trimmed.substringAfter(":").trim()
                }
                trimmed.startsWith("SUMMARY:", ignoreCase = true) -> {
                    summary = trimmed.substringAfter(":").trim()
                }
                trimmed.startsWith("TIPS:", ignoreCase = true) -> {
                    val items = trimmed.substringAfter(":").split(";")
                    tips.addAll(items.map { it.trim().removePrefix("-").trim() }.filter { it.isNotBlank() })
                }
            }
        }

        return ActivityRecommendation(
            activityName = activityName,
            isRecommended = recommended,
            recommendationSummary = summary.ifBlank { "Conditions are suitable for $activityName in ${weather.city.name}." },
            bestTimeWindow = bestWindow,
            safetyTips = tips.ifEmpty { listOf("Stay hydrated", "Monitor local conditions") }
        )
    }

    private fun parseWardrobeRecommendation(
        text: String,
        weather: CompleteWeatherData
    ): WardrobeRecommendation {
        var summary = "Dress comfortably for current conditions."
        val layers = mutableListOf<String>()
        val accessories = mutableListOf<String>()
        var umbrella = weather.precipitationMm > 0.0 || weather.currentPrecipProb >= 40

        for (line in text.lines()) {
            val trimmed = line.trim()
            when {
                trimmed.startsWith("SUMMARY:", ignoreCase = true) -> {
                    summary = trimmed.substringAfter(":").trim()
                }
                trimmed.startsWith("LAYERS:", ignoreCase = true) -> {
                    layers.addAll(trimmed.substringAfter(":").split(",").map { it.trim() }.filter { it.isNotBlank() })
                }
                trimmed.startsWith("ACCESSORIES:", ignoreCase = true) -> {
                    accessories.addAll(trimmed.substringAfter(":").split(",").map { it.trim() }.filter { it.isNotBlank() })
                }
                trimmed.startsWith("UMBRELLA:", ignoreCase = true) -> {
                    umbrella = trimmed.substringAfter(":").trim().startsWith("YES", ignoreCase = true)
                }
            }
        }

        return WardrobeRecommendation(
            summary = summary,
            primaryLayers = layers.ifEmpty { listOf("Comfortable top", "Seasonal outerwear") },
            accessories = accessories.ifEmpty { listOf("Sunglasses", "Comfortable footwear") },
            umbrellaNeeded = umbrella
        )
    }

    // ==========================================
    // Resilient Fallback Synthesizers
    // ==========================================

    private fun generateFallbackSummary(
        weather: CompleteWeatherData,
        isFahrenheit: Boolean
    ): WeatherSummaryResult {
        val tempUnit = if (isFahrenheit) "°F" else "°C"
        val curTemp = formatTemp(weather.currentTempC, isFahrenheit)
        val highTemp = formatTemp(weather.todayMaxTempC, isFahrenheit)
        val lowTemp = formatTemp(weather.todayMinTempC, isFahrenheit)
        val bestWindow = weather.hourlyList.filter { it.precipitationProb <= 20 }.firstOrNull()?.hourLabel ?: "2:00 PM"

        val clothing = when {
            weather.currentTempC < 8.0 -> "Heavy insulated coat, thermal layers, and warm footwear."
            weather.currentTempC in 8.0..15.0 -> "Cozy sweater or layered jacket with long pants."
            weather.currentTempC in 15.1..23.0 -> "Light breathable jacket, long sleeves, or cotton casuals."
            else -> "Lightweight breathable fabrics, shorts, and sunglasses."
        }

        val caution = if (weather.activeAlerts.isNotEmpty()) {
            weather.activeAlerts.first().headline
        } else if (weather.currentPrecipProb >= 50) {
            "High probability of rain showers today."
        } else if (weather.currentUvIndex >= 7.0) {
            "Very high UV index; apply SPF 30+ sun protection."
        } else null

        return WeatherSummaryResult(
            headline = "${weather.condition.title} with Highs of $highTemp$tempUnit in ${weather.city.name}",
            narrativeSummary = "${weather.city.name} is experiencing ${weather.condition.title.lowercase(Locale.ROOT)} conditions at $curTemp$tempUnit, reaching a daily peak of $highTemp$tempUnit and dropping to $lowTemp$tempUnit tonight.",
            clothingAdvice = clothing,
            outdoorWindow = "Best outdoor conditions expected around $bestWindow.",
            cautionNote = caution,
            keyHighlights = listOf(
                "${weather.condition.title} conditions",
                "Humidity at ${weather.humidityPct}%",
                "Rain probability: ${weather.currentPrecipProb}%"
            ),
            rawAiResponse = "Rule-based synthesis"
        )
    }

    private fun generateFallbackBriefing(weather: CompleteWeatherData, isFahrenheit: Boolean): String {
        val tempUnit = if (isFahrenheit) "°F" else "°C"
        val curTemp = formatTemp(weather.currentTempC, isFahrenheit)
        val bestWindow = weather.hourlyList.filter { it.precipitationProb <= 20 }.firstOrNull()?.hourLabel ?: "mid-afternoon"
        return "${weather.city.name} is currently $curTemp$tempUnit with ${weather.condition.title.lowercase(Locale.ROOT)}. Optimal window for outdoor activities is around $bestWindow with a ${weather.currentPrecipProb}% chance of rain."
    }

    private fun fallbackActivityRecommendation(activity: String, weather: CompleteWeatherData): ActivityRecommendation {
        val isGood = weather.precipitationMm < 2.0 && weather.windSpeedKmh < 35.0 && weather.currentTempC in 10.0..32.0
        val bestWindow = weather.hourlyList.minByOrNull { it.precipitationProb }?.hourLabel ?: "Late Morning"
        return ActivityRecommendation(
            activityName = activity,
            isRecommended = isGood,
            recommendationSummary = if (isGood) {
                "Conditions in ${weather.city.name} are favorable for $activity with mild weather and low rain chance."
            } else {
                "Caution is advised for $activity due to weather conditions in ${weather.city.name}."
            },
            bestTimeWindow = "Around $bestWindow",
            safetyTips = listOf("Check real-time radar before heading out", "Stay hydrated and wear appropriate layers")
        )
    }

    private fun fallbackWardrobeRecommendation(weather: CompleteWeatherData): WardrobeRecommendation {
        val needsUmbrella = weather.precipitationMm > 0.0 || weather.currentPrecipProb >= 40
        val layers = when {
            weather.currentTempC < 10.0 -> listOf("Thermal base", "Wool knit sweater", "Winter coat")
            weather.currentTempC in 10.0..20.0 -> listOf("Light sweater", "Windbreaker or cardigan")
            else -> listOf("Breathable cotton tee", "Shorts or light trousers")
        }
        val accessories = mutableListOf("Comfortable shoes")
        if (weather.currentUvIndex >= 5.0) accessories.add("UV sunglasses & sunscreen")
        if (needsUmbrella) accessories.add("Compact rain umbrella")

        return WardrobeRecommendation(
            summary = "Dress in adaptable layers suitable for ${weather.currentTempC.toInt()}°C weather.",
            primaryLayers = layers,
            accessories = accessories,
            umbrellaNeeded = needsUmbrella
        )
    }

    private fun fallbackAnswerQuestion(query: String, weather: CompleteWeatherData, isFahrenheit: Boolean): String {
        val tempUnit = if (isFahrenheit) "°F" else "°C"
        val curTemp = formatTemp(weather.currentTempC, isFahrenheit)
        val q = query.lowercase(Locale.ROOT)
        return when {
            q.contains("rain") || q.contains("umbrella") -> {
                if (weather.currentPrecipProb >= 40) {
                    "Yes, there is a ${weather.currentPrecipProb}% chance of rain in ${weather.city.name} today. It is advisable to bring an umbrella."
                } else {
                    "Rain is unlikely in ${weather.city.name} today with only a ${weather.currentPrecipProb}% chance."
                }
            }
            q.contains("cold") || q.contains("warm") || q.contains("hot") || q.contains("temp") -> {
                "The temperature in ${weather.city.name} is currently $curTemp$tempUnit with ${weather.condition.title.lowercase(Locale.ROOT)}."
            }
            else -> {
                "Current conditions in ${weather.city.name}: $curTemp$tempUnit, ${weather.condition.title}, with a ${weather.currentPrecipProb}% chance of precipitation."
            }
        }
    }

    companion object {
        private const val TAG = "WeatherAiSummaryRepo"
    }
}
